services:
  web:
    # Берем Dockerfile из каталога app
    build:
      context: .
      dockerfile: /app/Dockerfile
    # Запускаем тестовый сервер
    command: uvicorn app.main:app --host 0.0.0.0
    # Открываем порт 8000 внутри и снаружи
    ports:
      - 8000:8000